version: '3.8'

services:
  wallet:
    image: wallet:latest
    restart: on-failure
    volumes:
      - "./db:/opt/wallet/db"
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DB_POOL_SIZE: 5
      DB_FILE: /opt/wallet/db/prod-db