package io.cyberbarrista.wallet.rest.model

import org.jetbrains.exposed.sql.ResultRow
import java.util.UUID

// TODO Make this code autogenerated too

data class PlayerDto(
    val id: Long,
    val balance: Double,
)

data class PaymentTransactionDto(
    val uuid: UUID,
    val paymentValue: Double,
    val playerId: Long,
    val status: Status,
) {
    enum class Status {
        SUCCESSFUL,
        FAILED,
    }
}

fun ResultRow.toPlayerDto() = PlayerDto(
    id = this[Player.id].value,
    balance = this[Player.balance],
)

fun ResultRow.toPaymentTransactionDto() = PaymentTransactionDto(
    uuid = this[PaymentTransaction.id].value,
    paymentValue = this[PaymentTransaction.paymentValue],
    playerId = this[PaymentTransaction.playerId],
    status = enumValueOf(this[PaymentTransaction.status]),
)
